# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\админ\Desktop\add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color:#FF7F50")
        self.RegistrLabel = QtWidgets.QLabel(Form)
        self.RegistrLabel.setGeometry(QtCore.QRect(20, 10, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        self.RegistrLabel.setFont(font)
        self.RegistrLabel.setObjectName("RegistrLabel")
        self.createLog_2 = QtWidgets.QTextEdit(Form)
        self.createLog_2.setGeometry(QtCore.QRect(40, 110, 321, 41))
        self.createLog_2.setToolTipDuration(0)
        self.createLog_2.setStyleSheet("background-color:#ffa852")
        self.createLog_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.createLog_2.setLineWidth(0)
        self.createLog_2.setTabChangesFocus(False)
        self.createLog_2.setDocumentTitle("")
        self.createLog_2.setOverwriteMode(False)
        self.createLog_2.setAcceptRichText(True)
        self.createLog_2.setPlaceholderText("")
        self.createLog_2.setObjectName("createLog_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 180, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFriendButt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addFriendButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.addFriendButt.setDefault(False)
        self.addFriendButt.setObjectName("addFriendButt")
        self.horizontalLayout.addWidget(self.addFriendButt)
        self.cancelButt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.cancelButt.setDefault(False)
        self.cancelButt.setObjectName("cancelButt")
        self.horizontalLayout.addWidget(self.cancelButt)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "addRem"))
        self.RegistrLabel.setText(_translate("Form", "Добавить участника"))
        self.createLog_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.addFriendButt.setText(_translate("Form", "Добавить"))
        self.cancelButt.setText(_translate("Form", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
