# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\админ\Desktop\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 555)
        Form.setMouseTracking(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:#FF7F50")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 20, 331, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(80, 80, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.addEventButt = QtWidgets.QPushButton(Form)
        self.addEventButt.setGeometry(QtCore.QRect(410, 440, 259, 39))
        self.addEventButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.addEventButt.setDefault(False)
        self.addEventButt.setObjectName("addEventButt")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(150, 110, 401, 221))
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(350)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(53)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.clearButt = QtWidgets.QPushButton(Form)
        self.clearButt.setGeometry(QtCore.QRect(410, 490, 259, 39))
        self.clearButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.clearButt.setDefault(False)
        self.clearButt.setObjectName("clearButt")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 400, 251, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkLogButt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.checkLogButt.setEnabled(True)
        self.checkLogButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.checkLogButt.setDefault(False)
        self.checkLogButt.setObjectName("checkLogButt")
        self.verticalLayout.addWidget(self.checkLogButt)
        self.addRememberButt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addRememberButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.addRememberButt.setDefault(False)
        self.addRememberButt.setObjectName("addRememberButt")
        self.verticalLayout.addWidget(self.addRememberButt)
        self.ExitButt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ExitButt.setEnabled(True)
        self.ExitButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.ExitButt.setDefault(False)
        self.ExitButt.setObjectName("ExitButt")
        self.verticalLayout.addWidget(self.ExitButt)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Ваши напоминания"))
        self.addEventButt.setText(_translate("Form", "Добавить событие"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Строка"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Иван"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Напоминание"))
        self.clearButt.setText(_translate("Form", "Очистить"))
        self.checkLogButt.setText(_translate("Form", "Посмтотреть входы"))
        self.addRememberButt.setText(_translate("Form", "Добавить участников"))
        self.ExitButt.setText(_translate("Form", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
