# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\админ\Desktop\registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 450)
        Form.setStyleSheet("background-color:#FF7F50")
        self.RegistrLabel = QtWidgets.QLabel(Form)
        self.RegistrLabel.setGeometry(QtCore.QRect(120, 30, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        self.RegistrLabel.setFont(font)
        self.RegistrLabel.setObjectName("RegistrLabel")
        self.createPass = QtWidgets.QTextEdit(Form)
        self.createPass.setGeometry(QtCore.QRect(100, 210, 261, 31))
        self.createPass.setToolTipDuration(0)
        self.createPass.setStyleSheet("background-color:#ffa852")
        self.createPass.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.createPass.setLineWidth(0)
        self.createPass.setTabChangesFocus(False)
        self.createPass.setObjectName("createPass")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 131, 21))
        self.label_4.setObjectName("label_4")
        self.createLog = QtWidgets.QTextEdit(Form)
        self.createLog.setGeometry(QtCore.QRect(100, 140, 261, 31))
        self.createLog.setToolTipDuration(0)
        self.createLog.setStyleSheet("background-color:#ffa852")
        self.createLog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.createLog.setLineWidth(0)
        self.createLog.setTabChangesFocus(False)
        self.createLog.setObjectName("createLog")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 250, 131, 21))
        self.label_5.setObjectName("label_5")
        self.sendCode = QtWidgets.QTextEdit(Form)
        self.sendCode.setGeometry(QtCore.QRect(100, 280, 261, 31))
        self.sendCode.setToolTipDuration(0)
        self.sendCode.setStyleSheet("background-color:#ffa852")
        self.sendCode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sendCode.setLineWidth(0)
        self.sendCode.setTabChangesFocus(False)
        self.sendCode.setObjectName("sendCode")
        self.finishRegButt = QtWidgets.QPushButton(Form)
        self.finishRegButt.setGeometry(QtCore.QRect(130, 340, 191, 41))
        self.finishRegButt.setStyleSheet(" display: inline-block;\n"
"    text-decoration: none;\n"
"    background-color: #ffa852;\n"
"    color: #006089;\n"
"    border: 3px solid #d9812f;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    padding: 7px 10px; \n"
"    transition: all 0.8s ease;")
        self.finishRegButt.setDefault(False)
        self.finishRegButt.setObjectName("finishRegButt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RegistrLabel.setText(_translate("Form", "Регистрация"))
        self.createPass.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Form", "Придумайте пароль"))
        self.label_4.setText(_translate("Form", "Придумайте логин"))
        self.createLog.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("Form", "Код подтверждения"))
        self.sendCode.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.finishRegButt.setText(_translate("Form", "Завершить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
